logging.level:
  root: INFO

management:
  endpoint:
    health:
      show-details: always
      
server:
  port: 8083
  servlet:
    context-path: /customers
    
spring.jackson.time-zone: America/Lima
spring.jackson.locale: es_PE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customers?useSSL=false
    username: root
    password: admin  
  flyway:
    baseline-on-migrate: true
    enabled: true